[loggers]
keys = root,simpleLogger,subLogger

[handlers]
keys = consoleHandler

[formatters]
keys = simpleFormatter

[logger_root]
level = INFO
handlers = consoleHandler

[logger_simpleLogger]
level = INFO
handlers = consoleHandler
qualname = simpleLogger
propagate = 0

[logger_subLogger]
level = INFO
handlers = consoleHandler
qualname = subLogger
propagate = 0

[handler_consoleHandler]
class = StreamHandler
level = INFO
formatter = simpleFormatter
args = (sys.stdout,)

[formatter_simpleFormatter]
format = [%(asctime)s] %(levelname)s - %(message)s
