[loggers]
keys = root,simpleLogger

[handlers]
keys = consoleHandler,mainFileHandler,detectionFileHandler

[formatters]
keys = simpleFormatter

[logger_root]
level = INFO
handlers = consoleHandler

[logger_simpleLogger]
level = INFO
handlers = consoleHandler,mainFileHandler
qualname = simpleLogger
propagate = 0

[handler_consoleHandler]
class = StreamHandler
level = INFO
formatter = simpleFormatter
args = (sys.stdout,)

[handler_mainFileHandler]
class = handlers.TimedRotatingFileHandler
level = INFO
formatter = simpleFormatter
args = ("logs/main_log.log","S",5)

[handler_detectionFileHandler]
class = handlers.TimedRotatingFileHandler
level = INFO
formatter = simpleFormatter
args = ("logs/detection_log.log","midnight")

[formatter_simpleFormatter]
format = [%(asctime)s] %(levelname)s - %(message)s
datefmt = %Y/%m/%d %H:%M:%S
