[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "logging-test"
version = "1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "toml",
]

[tool.setuptools.packages.find]
where = ["src"]